spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: orderdb

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
          auto-create-topics: true

      function:
        definition: orderShippingRequestProducer;orderShippingStatusConsumer;orderCanceledProducer

      bindings:
        orderShippingRequestProducer-out-0:
          destination: order-shipping-request
        orderShippingStatusConsumer-in-0:
          destination: order-shipping-status
        orderCanceledProducer-out-0:
          destination: order-canceled